### ISSUE TITLE
Unable to watermark small size of stl

### ISSUE THREAD

**Issue by ahmadharminto** [powertomato/STLenographer#1]
Hi, do you know how to deal with small size of stl file? Seems it will be catched by this condition https://github.com/powertomato/STLenographer/blob/dc8d327b2cceb4feb2a583d27dacd6636d893a52/STLenographer/STLenographer.cs#L214

**Comment by powertomato** [comment]
The data is stored in the non-significant bits of the vertices of the file. So if there are not enough of them, it will fail.
I'm not sure it's that line, where it would fail, though. I thought I have built in a check for that (it's 5 years I've touched that code).
As a workaround you could try to subdivide the surface of the object to generate more vertices. Most design software will allow to do that.

If you upload a file that I could use to reproduce the error, I can have a closer look. It should not crash and I could put in a more meaningful error message and suggest the sub-division workaround there.

**Comment by ahmadharminto** [comment]
Hi @powertomato , thanks for the response. Sure, I will try to generate more vertices. If you don't mind, could you please to try to watermark these [files](https://drive.google.com/file/d/18xYvf2xq9eeSnaAYRxjXbYfs-r-Ir6l3/view?usp=sharing) for testing if they can be watermarked? Because last time I tried, it will be caught by that condition. Many thanks for considering my request. Anyway, do you accept donations? I would like to give you some appreciation.

**Comment by powertomato** [comment]
Hi @ahmadharminto,

As I suspected the issue with the files is that they don't contain enough unique vertices to hide a large amout of data. So the issue does not seem to be a bug (Unless there is a crash and not just a warning message; in this case please provide me with exact input data).

Anyway the workaround with the subdivision is now performed automatically until the provided data fits. This will, of course, make the file bigger.

Those changes are published in a new release [beta_2](https://github.com/powertomato/STLenographer/releases/tag/beta_2). Could you have a look if your issue is resolved?

As for the donations, I added a button to the readme on https://github.com/powertomato/STLenographer.

**Comment by ahmadharminto** [comment]
Hi @powertomato ,

Thank you. Sure, I'll have a look and I'll let you know if it solves my issue.
Many thanks for considering my request.

**Comment by ahmadharminto** [comment]
Hi @powertomato ,

After few days / months testing, the new release beta_2 looks good to me.
Thank you in advance mate! I do appreciate! 🍻
